[32m2023-01-05 13:13:44 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 25db84ff-fdab-45d8-9c1b-6f09b767a9b3 - 4621 - LOGS_CAPTURED - Started capturing logs in process (pid: 4621).
[32m2023-01-05 13:13:44 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 25db84ff-fdab-45d8-9c1b-6f09b767a9b3 - 4621 - stg_orders - STEP_START - Started execution of step "stg_orders".
[32m2023-01-05 13:13:45 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 25db84ff-fdab-45d8-9c1b-6f09b767a9b3 - 4621 - stg_orders - STEP_OUTPUT - Yielded output "result" of type "SQL". (Type check passed).
[32m2023-01-05 13:13:47 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 25db84ff-fdab-45d8-9c1b-6f09b767a9b3 - 4621 - stg_orders - STEP_FAILURE - Execution of step "stg_orders" failed.

dagster._core.errors.DagsterExecutionHandleOutputError: Error occurred while handling output "result" of step "stg_orders"::

duckdb.Error: Invalid Error: HTTP HEAD error on 'http://localhost:4566/datalake/stg_orders.parquet' (Error code 2)

Stack Trace:
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
    yield
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagster/_utils/__init__.py", line 458, in iterate_with_context
    next_output = next(iterator)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagster/_core/execution/plan/execute_step.py", line 626, in _gen_fn
    gen_output = output_manager.handle_output(output_context, output.value)
  File "/workspace/modern-datastack/cloned/dagster-poor-mans-data-lake/jaffle/duckpond.py", line 84, in handle_output
    self.duckdb.query(
  File "/workspace/modern-datastack/cloned/dagster-poor-mans-data-lake/jaffle/duckpond.py", line 56, in query
    result = db.query(sql_to_string(select_statement))
[0m
